#include <furi.h>

/* generated by fbt from .png files in images folder */
#include <ham70_icons.h>

int32_t ham70_app(void* p) {
    UNUSED(p);
    FURI_LOG_I("TEST", "Hello world");
    FURI_LOG_I("TEST", "I'm ham70!");

    return 0;
}
